export default function Home() {
  return (
    <>
      <div>
        <title>AAP Sink Utforsker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </div>
      <main>
        <h1>AAP Sink Utforsker</h1>
      </main>
    </>
  )
}
